export const mockVideoList = [
    {
        url: "https://www.youtube.com/embed/DTJPfROVxGE",
        genre: "comedy",
        width: "344",
        height: "611",
        title: "goodby",
    },
    {
        url: "https://www.youtube.com/embed/N_aGQyyf91Q",
        genre: "comedy",
        width: "344",
        height: "611",
        title: "kiss",
    },
    {
        url: "https://www.youtube.com/embed/bMljQglcxj4",
        genre: "comedy",
        width: "344",
        height: "611",
        title: "bali",
    },
    {
        url: "https://www.youtube.com/embed/zHCVjJyeDRY",
        genre: "comedy",
        width: "344",
        height: "611",
        title: "date",
    },
    {
        url: "https://www.youtube.com/embed/s2MEzfZHx_Y",
        genre: "edu",
        width: "344",
        height: "611",
        title: "css",
    },
    {
        url: "https://www.youtube.com/embed/d3GtZrk70Fw",
        genre: "edu",
        width: "344",
        height: "611",
        title: "css",
    },
    {
        url: "https://www.youtube.com/embed/3r86wJTq9Hc",
        genre: "edu",
        width: "344",
        height: "611",
        title: "js",
    },
    {
        url: "https://www.youtube.com/embed/rhBW64ZZrjE",
        genre: "edu",
        width: "344",
        height: "611",
        title: "js",
    },
    {
        url: "https://www.youtube.com/embed/xOHGc1i7JCs",
        genre: "comedy",
        width: "675",
        height: "506",
        title: "friends. cheese pie",
    },
    {
        url: "https://www.youtube.com/embed/ssg7ZL74lxc",
        genre: "sports",
        width: "344",
        height: "611",
        title: "Ronaldinho",
    },
    {
        url: "https://www.youtube.com/embed/VpfyfLqmIDU",
        genre: "sports",
        width: "344",
        height: "611",
        title: "Rafael Nadal",
    },
    {
        url: "https://www.youtube.com/embed/jdE9rGQY0cM",
        genre: "sports",
        width: "344",
        height: "611",
        title: "Wayne Gretzky",
    },
    {
        url: "https://www.youtube.com/embed/iN3EenddGn8",
        genre: "sports",
        width: "344",
        height: "611",
        title: "Jordan",
    },
    {
        url: "https://www.youtube.com/embed/pVSEU9RlzK8",
        genre: "other",
        width: "344",
        height: "611",
        title: "Кращі психологи - це друзі!",
    },
    {
        url: "https://www.youtube.com/embed/Qyv9zSAn2QQ",
        genre: "other",
        width: "900",
        height: "506",
        title: "БОЙОВИЙ СУРЖИК",
    },
];
